schema_version: 1

context:
  name: de-bundestag-lobbyregister
  version: 0.1.0

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/de-bundestag-lobbyregister-${{ version }}.tar.gz
  sha256: 33258de532bae77f3579a09c26fb3543bbad853aa2a3509a5779523d63888065

build:
  number: 2
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - poetry
  run:
    - python >=${{ python_min }}
    - python-dateutil
    - urllib3 >=1.25.3

tests:
  - python:
      imports:
        - deutschland.bundestag_lobbyregister
      python_version: ${{ python_min }}.*
  - requirements:
      run:
        - pip
        - python ${{ python_min }}.*
    script:
      - pip check

about:
  summary: "Bundestag: Lobbyregister"
  license: Apache-2.0
  license_file:
    - LICENSE
  homepage: https://github.com/bundesAPI/bundestag-lobbyregister-api

extra:
  recipe-maintainers:
    - jan-janssen
